name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest #macos-15 
# -project NetworkingTutorial/NetworkingTutorial.xcodeproj
          # -scheme NetworkingTutorial
           # - name: Set Default Scheme
      #   run: |
      #     scheme_list=$(xcodebuild -list -json)
      #     default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
      #     echo $default | cat >default
      #     echo Using default scheme: $default
    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - name: Build
        env:
          scheme: NetworkingTutorial
          platform: ${{ 'iOS Simulator' }}
        run: |
          xcodebuild clean build test -project NetworkingTutorial/NetworkingTutorial.xcodeproj -scheme "NetworkingTutorial" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 17,OS=26.2" ONLY_ACTIVE_ARCH=YES SWIFT_TREAT_WARNINGS_AS_ERRORS=YES OTHER_SWIFT_FLAGS="-D ED_SKIP_SWIFT_FORMAT"
          # xcrun simctl list devices available
          # clean build test -showdestinations
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          # device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          # if [ $scheme = NetworkingTutorial ]; then scheme=$(cat NetworkingTutorial); fi
          # if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          # file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          # xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"
      # - name: Test
      #   env:
      #     scheme: NetworkingTutorial
      #     platform: ${{ 'iOS Simulator' }}
      #   run: |
      #     # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
      #     # device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
      #     # if [ $scheme = NetworkingTutorial ]; then scheme=$(cat NetworkingTutorial); fi
      #     # if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
      #     # file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
      #     xcodebuild test-without-building -project NetworkingTutorial/NetworkingTutorial.xcodeproj -scheme "NetworkingTutorial" -destination "platform=iOS Simulator,name=iPhone 17,OS=26.2"
